# Welcome to Jekyll!
#

# Site settings
title: Copa Flick
description: |
  This web page is for
  Flick cup organization
owner: Cindy Correa # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: ccorreaconejo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://copaflick.github.io" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/copaflick.github.io
  facebook-official: https://facebook.com/Bienenhockeyclub
  instagram: https://instagram.com/bienen_h.c
  #email: /contact/
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
